export enum ENUM_STATUS {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    INIT = "INIT"
};

export enum ENUM_MODEL {
    AUTH = "AUTH",
    USER = "USER",
    ROLE = "ROLE",
    MENU = "MENU",
    AUTO_UPLOAD = "AUTO_UPLOAD",
    AUTO_MOVIE = "AUTO_MOVIE",
    CATEGORY = "CATEGORY",
    MOVIE = "MOVIE",
    MOVIE_STATUS = "MOVIE_STATUS",
    PERMISSION = "PERMISSION",
    EPISODE = "EPISODE",
    VIDEO = "VIDEO",
    IMAGE = "IMAGE",
    STATUS = "STATUS",
    VIEWS = "VIEWS",
    LIKES = "LIKES",
    SETTING = "SETTING",
    SPLIT_FILE = "SPLIT_FILE",
    FAVORITE = "FAVORITE",
    ERROR_MOVIE = "ERROR_MOVIE",
    COMMENT = "COMMENT",
    VALID_ADDRESS = "VALID_ADDRESS",
    CAPTCHA = "CAPTCHA",
    MOVIE_GROUP = "MOVIE_GROUP",
    PART_MOVIE = "PART_MOVIE",
    FANSUB = "FANSUB",
    VIDEO_LINK = "VIDEO_LINK",
    VOCABULARY = "VOCABULARY"
}